namespace PoeLib.Common;

public static class BaseTypes
{
    public static string[] Bases = {
        "Short Bow",
        "Long Bow",
        "Composite Bow",
        "Recurve Bow",
        "Bone Bow",
        "Royal Bow",
        "Hedron Bow",
        "Death Bow",
        "Grove Bow",
        "Reflex Bow",
        "Decurve Bow",
        "Compound Bow",
        "Sniper Bow",
        "Ivory Bow",
        "Foundry Bow",
        "Highborn Bow",
        "Decimation Bow",
        "Thicket Bow",
        "Steelwood Bow",
        "Citadel Bow",
        "Ranger Bow",
        "Assassin Bow",
        "Spine Bow",
        "Imperial Bow",
        "Harbinger Bow",
        "Solarine Bow",
        "Maraketh Bow",
        "Nailed Fist",
        "Sharktooth Claw",
        "Awl",
        "Cat's Paw",
        "Blinder",
        "Timeworn Claw",
        "Sparkling Claw",
        "Shadow Fangs",
        "Fright Claw",
        "Double Claw",
        "Thresher Claw",
        "Gouger",
        "Tiger's Paw",
        "Gut Ripper",
        "Prehistoric Claw",
        "Malign Fangs",
        "Noble Claw",
        "Eagle Claw",
        "Twin Claw",
        "Great White Claw",
        "Throat Stabber",
        "Hellion's Paw",
        "Eye Gouger",
        "Vaal Claw",
        "Imperial Claw",
        "Terror Claw",
        "Void Fangs",
        "Gemini Claw",
        "Glass Shank",
        "Skinning Knife",
        "Stiletto",
        "Hollowpoint Dagger",
        "Flaying Knife",
        "Prong Dagger",
        "Poignard",
        "Pressurised Dagger",
        "Trisula",
        "Gutting Knife",
        "Ambusher",
        "Sai",
        "Pneumatic Dagger",
        "Rusted Hatchet",
        "Jade Hatchet",
        "Boarding Axe",
        "Cleaver",
        "Broad Axe",
        "Arming Axe",
        "Decorative Axe",
        "Maltreatment Axe",
        "Spectral Axe",
        "Etched Hatchet",
        "Jasper Axe",
        "Tomahawk",
        "Wrist Chopper",
        "War Axe",
        "Chest Splitter",
        "Disapprobation Axe",
        "Ceremonial Axe",
        "Wraith Axe",
        "Engraved Hatchet",
        "Karui Axe",
        "Siege Axe",
        "Reaver Axe",
        "Butcher Axe",
        "Vaal Hatchet",
        "Royal Axe",
        "Infernal Axe",
        "Psychotic Axe",
        "Runic Hatchet",
        "Driftwood Club",
        "Tribal Club",
        "Spiked Club",
        "Stone Hammer",
        "War Hammer",
        "Bladed Mace",
        "Ceremonial Mace",
        "Flare Mace",
        "Dream Mace",
        "Wyrm Mace",
        "Petrified Club",
        "Barbed Club",
        "Rock Breaker",
        "Battle Hammer",
        "Flanged Mace",
        "Crack Mace",
        "Ornate Mace",
        "Phantom Mace",
        "Dragon Mace",
        "Ancestral Club",
        "Tenderizer",
        "Gavel",
        "Legion Hammer",
        "Pernach",
        "Auric Mace",
        "Nightmare Mace",
        "Boom Mace",
        "Behemoth Mace",
        "Rusted Sword",
        "Charan's Sword",
        "Copper Sword",
        "Sabre",
        "Broad Sword",
        "War Sword",
        "Ancient Sword",
        "Elegant Sword",
        "Fickle Spiritblade",
        "Dusk Blade",
        "Hook Sword",
        "Variscite Blade",
        "Cutlass",
        "Baselard",
        "Battle Sword",
        "Elder Sword",
        "Graceful Sword",
        "Capricious Spiritblade",
        "Twilight Blade",
        "Grappler",
        "Gemstone Sword",
        "Corsair Sword",
        "Gladius",
        "Legion Sword",
        "Vaal Blade",
        "Eternal Sword",
        "Midnight Blade",
        "Anarchic Spiritblade",
        "Tiger Hook",
        "Carving Knife",
        "Boot Knife",
        "Copper Kris",
        "Skean",
        "Flickerflame Blade",
        "Imp Dagger",
        "Butcher Knife",
        "Boot Blade",
        "Golden Kris",
        "Royal Skean",
        "Flashfire Blade",
        "Fiend Dagger",
        "Slaughter Knife",
        "Ezomyte Dagger",
        "Platinum Kris",
        "Imperial Skean",
        "Demon Dagger",
        "Infernal Blade",
        "Driftwood Sceptre",
        "Darkwood Sceptre",
        "Bronze Sceptre",
        "Quartz Sceptre",
        "Iron Sceptre",
        "Ochre Sceptre",
        "Ritual Sceptre",
        "Oscillating Sceptre",
        "Shadow Sceptre",
        "Grinning Fetish",
        "Horned Sceptre",
        "Sekhem",
        "Crystal Sceptre",
        "Lead Sceptre",
        "Blood Sceptre",
        "Royal Sceptre",
        "Stabilising Sceptre",
        "Abyssal Sceptre",
        "Stag Sceptre",
        "Karui Sceptre",
        "Tyrant's Sekhem",
        "Opal Sceptre",
        "Platinum Sceptre",
        "Vaal Sceptre",
        "Carnal Sceptre",
        "Void Sceptre",
        "Alternating Sceptre",
        "Sambar Sceptre",
        "Gnarled Branch",
        "Primitive Staff",
        "Long Staff",
        "Royal Staff",
        "Transformer Staff",
        "Crescent Staff",
        "Woodful Staff",
        "Quarterstaff",
        "Reciprocation Staff",
        "Highborn Staff",
        "Moon Staff",
        "Primordial Staff",
        "Lathi",
        "Imperial Staff",
        "Eclipse Staff",
        "Battery Staff",
        "Rusted Spike",
        "Whalebone Rapier",
        "Battered Foil",
        "Basket Rapier",
        "Jagged Foil",
        "Antique Rapier",
        "Elegant Foil",
        "Thorn Rapier",
        "Smallsword",
        "Wyrmbone Rapier",
        "Burnished Foil",
        "Estoc",
        "Serrated Foil",
        "Primeval Rapier",
        "Fancy Foil",
        "Apex Rapier",
        "Courtesan Sword",
        "Dragonbone Rapier",
        "Tempered Foil",
        "Pecoraro",
        "Spiraled Foil",
        "Vaal Rapier",
        "Jewelled Foil",
        "Harpy Rapier",
        "Dragoon Sword",
        "Stone Axe",
        "Jade Chopper",
        "Woodsplitter",
        "Poleaxe",
        "Double Axe",
        "Gilded Axe",
        "Prime Cleaver",
        "Shadow Axe",
        "Dagger Axe",
        "Jasper Chopper",
        "Timber Axe",
        "Headsman Axe",
        "Labrys",
        "Honed Cleaver",
        "Noble Axe",
        "Abyssal Axe",
        "Karui Chopper",
        "Talon Axe",
        "Sundering Axe",
        "Ezomyte Axe",
        "Vaal Axe",
        "Despot Axe",
        "Void Axe",
        "Fleshripper",
        "Apex Cleaver",
        "Driftwood Maul",
        "Tribal Maul",
        "Mallet",
        "Sledgehammer",
        "Jagged Maul",
        "Brass Maul",
        "Blunt Force Condenser",
        "Fright Maul",
        "Morning Star",
        "Totemic Maul",
        "Great Mallet",
        "Steelhead",
        "Spiny Maul",
        "Crushing Force Magnifier",
        "Plated Maul",
        "Dread Maul",
        "Solar Maul",
        "Karui Maul",
        "Colossus Mallet",
        "Piledriver",
        "Meatgrinder",
        "Imperial Maul",
        "Terror Maul",
        "Coronal Maul",
        "Impact Force Propagator",
        "Corroded Blade",
        "Longsword",
        "Bastard Sword",
        "Two-Handed Sword",
        "Etched Greatsword",
        "Ornate Sword",
        "Rebuking Blade",
        "Spectral Sword",
        "Curved Blade",
        "Butcher Sword",
        "Footman Sword",
        "Highland Blade",
        "Engraved Greatsword",
        "Blasting Blade",
        "Tiger Sword",
        "Wraith Sword",
        "Lithe Blade",
        "Headman's Sword",
        "Reaver Sword",
        "Ezomyte Blade",
        "Vaal Greatsword",
        "Lion Sword",
        "Infernal Sword",
        "Exquisite Blade",
        "Banishing Blade",
        "Driftwood Wand",
        "Goat's Horn",
        "Carved Wand",
        "Quartz Wand",
        "Spiraled Wand",
        "Sage Wand",
        "Assembler Wand",
        "Pagan Wand",
        "Faun's Horn",
        "Engraved Wand",
        "Crystal Wand",
        "Serpent Wand",
        "Congregator Wand",
        "Omen Wand",
        "Heathen Wand",
        "Demon's Horn",
        "Imbued Wand",
        "Opal Wand",
        "Tornado Wand",
        "Prophecy Wand",
        "Accumulator Wand",
        "Profane Wand",
        "Convoking Wand",
        "Iron Staff",
        "Coiled Staff",
        "Capacity Rod",
        "Vile Staff",
        "Military Staff",
        "Serpentine Staff",
        "Potentiality Rod",
        "Foul Staff",
        "Ezomyte Staff",
        "Maelström Staff",
        "Judgement Staff",
        "Eventuality Rod",
        "Shabby Jerkin",
        "Simple Robe",
        "Padded Vest",
        "Chainmail Vest",
        "Scale Vest",
        "Chestplate",
        "Light Brigandine",
        "Chainmail Tunic",
        "Oiled Vest",
        "Strapped Leather",
        "Silken Vest",
        "Buckskin Tunic",
        "Copper Plate",
        "Scale Doublet",
        "Ringmail Coat",
        "Scholar's Robe",
        "Padded Jacket",
        "Golden Mantle",
        "Infantry Brigandine",
        "Chainmail Doublet",
        "War Plate",
        "Oiled Coat",
        "Silken Garb",
        "Wild Leather",
        "Full Leather",
        "Scarlet Raiment",
        "Mage's Vestment",
        "Full Plate",
        "Full Scale Armour",
        "Full Ringmail",
        "Full Chainmail",
        "Soldier's Brigandine",
        "Arena Plate",
        "Silk Robe",
        "Waxed Garb",
        "Sun Leather",
        "Holy Chainmail",
        "Thief's Garb",
        "Bone Armour",
        "Cabalist Regalia",
        "Lordly Plate",
        "Field Lamellar",
        "Eelskin Tunic",
        "Sage's Robe",
        "Bronze Plate",
        "Wyrmscale Doublet",
        "Latticed Ringmail",
        "Quilted Jacket",
        "Battle Plate",
        "Frontier Leather",
        "Silken Wrap",
        "Hussar Brigandine",
        "Crusader Chainmail",
        "Sleek Coat",
        "Glorious Leather",
        "Conjurer's Vestment",
        "Sun Plate",
        "Full Wyrmscale",
        "Ornate Ringmail",
        "Crimson Raiment",
        "Colosseum Plate",
        "Spidersilk Robe",
        "Coronal Leather",
        "Commander's Brigandine",
        "Chain Hauberk",
        "Lacquered Garb",
        "Cutthroat's Garb",
        "Destroyer Regalia",
        "Majestic Plate",
        "Battle Lamellar",
        "Devout Chainmail",
        "Savant's Robe",
        "Crypt Armour",
        "Sharkskin Tunic",
        "Golden Plate",
        "Dragonscale Doublet",
        "Loricated Ringmail",
        "Crusader Plate",
        "Sentinel Jacket",
        "Destiny Leather",
        "Necromancer Silks",
        "Desert Brigandine",
        "Conquest Chainmail",
        "Exquisite Leather",
        "Varnished Coat",
        "Astral Plate",
        "Occultist's Vestment",
        "Full Dragonscale",
        "Elegant Ringmail",
        "Widowsilk Robe",
        "Zodiac Leather",
        "Blood Raiment",
        "Gladiator Plate",
        "General's Brigandine",
        "Saint's Hauberk",
        "Glorious Plate",
        "Vaal Regalia",
        "Sadist Garb",
        "Assassin's Garb",
        "Triumphant Lamellar",
        "Saintly Chainmail",
        "Carnal Armour",
        "Sacrificial Garb",
        "Iron Greaves",
        "Rawhide Boots",
        "Wool Shoes",
        "Chain Boots",
        "Wrapped Boots",
        "Leatherscale Boots",
        "Steel Greaves",
        "Velvet Slippers",
        "Goathide Boots",
        "Ringmail Boots",
        "Strapped Boots",
        "Ironscale Boots",
        "Deerskin Boots",
        "Silk Slippers",
        "Plated Greaves",
        "Clasped Boots",
        "Mesh Boots",
        "Bronzescale Boots",
        "Scholar Boots",
        "Reinforced Greaves",
        "Nubuck Boots",
        "Shackled Boots",
        "Riveted Boots",
        "Steelscale Boots",
        "Antique Greaves",
        "Satin Slippers",
        "Eelskin Boots",
        "Zealot Boots",
        "Trapper Boots",
        "Serpentscale Boots",
        "Sharkskin Boots",
        "Samite Slippers",
        "Ancient Greaves",
        "Ambush Boots",
        "Soldier Boots",
        "Wyrmscale Boots",
        "Conjurer Boots",
        "Goliath Greaves",
        "Carnal Boots",
        "Shagreen Boots",
        "Legion Boots",
        "Hydrascale Boots",
        "Arcanist Slippers",
        "Vaal Greaves",
        "Stealth Boots",
        "Assassin's Boots",
        "Crusader Boots",
        "Dragonscale Boots",
        "Sorcerer Boots",
        "Titan Greaves",
        "Murder Boots",
        "Slink Boots",
        "Two-Toned Boots",
        "Iron Gauntlets",
        "Wool Gloves",
        "Rawhide Gloves",
        "Fishscale Gauntlets",
        "Wrapped Mitts",
        "Chain Gloves",
        "Goathide Gloves",
        "Plated Gauntlets",
        "Velvet Gloves",
        "Ironscale Gauntlets",
        "Strapped Mitts",
        "Ringmail Gloves",
        "Deerskin Gloves",
        "Bronze Gauntlets",
        "Silk Gloves",
        "Bronzescale Gauntlets",
        "Clasped Mitts",
        "Mesh Gloves",
        "Nubuck Gloves",
        "Steel Gauntlets",
        "Embroidered Gloves",
        "Steelscale Gauntlets",
        "Trapper Mitts",
        "Riveted Gloves",
        "Eelskin Gloves",
        "Antique Gauntlets",
        "Satin Gloves",
        "Zealot Gloves",
        "Serpentscale Gauntlets",
        "Sharkskin Gloves",
        "Ambush Mitts",
        "Samite Gloves",
        "Ancient Gauntlets",
        "Wyrmscale Gauntlets",
        "Carnal Mitts",
        "Soldier Gloves",
        "Goliath Gauntlets",
        "Shagreen Gloves",
        "Conjurer Gloves",
        "Legion Gloves",
        "Assassin's Mitts",
        "Hydrascale Gauntlets",
        "Arcanist Gloves",
        "Stealth Gloves",
        "Vaal Gauntlets",
        "Crusader Gloves",
        "Murder Mitts",
        "Dragonscale Gauntlets",
        "Sorcerer Gloves",
        "Titan Gauntlets",
        "Slink Gloves",
        "Spiked Gloves",
        "Fingerless Silk Gloves",
        "Gripped Gloves",
        "Iron Hat",
        "Vine Circlet",
        "Leather Cap",
        "Battered Helm",
        "Scare Mask",
        "Rusted Coif",
        "Cone Helmet",
        "Iron Circlet",
        "Plague Mask",
        "Tricorne",
        "Soldier Helmet",
        "Sallet",
        "Iron Mask",
        "Torture Cage",
        "Barbute Helmet",
        "Leather Hood",
        "Great Helmet",
        "Visored Sallet",
        "Tribal Circlet",
        "Close Helmet",
        "Festival Mask",
        "Wolf Pelt",
        "Crusader Helmet",
        "Gilded Sallet",
        "Bone Circlet",
        "Golden Mask",
        "Gladiator Helmet",
        "Secutor Helm",
        "Aventail Helmet",
        "Raven Mask",
        "Lunaris Circlet",
        "Reaver Helmet",
        "Hunter Hood",
        "Fencer Helm",
        "Zealot Helmet",
        "Callous Mask",
        "Noble Tricorne",
        "Siege Helmet",
        "Steel Circlet",
        "Lacquered Helmet",
        "Regicide Mask",
        "Great Crown",
        "Necromancer Circlet",
        "Ursine Pelt",
        "Samite Helmet",
        "Harlequin Mask",
        "Fluted Bascinet",
        "Magistrate Crown",
        "Solaris Circlet",
        "Ezomyte Burgonet",
        "Silken Hood",
        "Vaal Mask",
        "Pig-Faced Bascinet",
        "Prophet Crown",
        "Sinner Tricorne",
        "Royal Burgonet",
        "Mind Cage",
        "Deicide Mask",
        "Nightmare Bascinet",
        "Praetor Crown",
        "Eternal Burgonet",
        "Hubris Circlet",
        "Lion Pelt",
        "Bone Helmet",
        "Splintered Tower Shield",
        "Goathide Buckler",
        "Twig Spirit Shield",
        "Corroded Tower Shield",
        "Spiked Bundle",
        "Rotted Round Shield",
        "Plank Kite Shield",
        "Pine Buckler",
        "Yew Spirit Shield",
        "Rawhide Tower Shield",
        "Driftwood Spiked Shield",
        "Fir Round Shield",
        "Linden Kite Shield",
        "Bone Spirit Shield",
        "Painted Buckler",
        "Cedar Tower Shield",
        "Studded Round Shield",
        "Reinforced Kite Shield",
        "Alloyed Spiked Shield",
        "Tarnished Spirit Shield",
        "Hammered Buckler",
        "Copper Tower Shield",
        "Burnished Spiked Shield",
        "Layered Kite Shield",
        "Scarlet Round Shield",
        "Jingling Spirit Shield",
        "War Buckler",
        "Exothermic Tower Shield",
        "Endothermic Buckler",
        "Reinforced Tower Shield",
        "Exhausting Spirit Shield",
        "Splendid Round Shield",
        "Ornate Spiked Shield",
        "Brass Spirit Shield",
        "Ceremonial Kite Shield",
        "Gilded Buckler",
        "Painted Tower Shield",
        "Walnut Spirit Shield",
        "Oak Buckler",
        "Redwood Spiked Shield",
        "Buckskin Tower Shield",
        "Maple Round Shield",
        "Etched Kite Shield",
        "Ivory Spirit Shield",
        "Eled Buckler",
        "Mahogany Tower Shield",
        "Spiked Round Shield",
        "Ancient Spirit Shield",
        "Compound Spiked Shield",
        "Corrugated Buckler",
        "Steel Kite Shield",
        "Bronze Tower Shield",
        "Chiming Spirit Shield",
        "Polished Spiked Shield",
        "Crimson Round Shield",
        "Polar Buckler",
        "Magmatic Tower Shield",
        "Battle Buckler",
        "Laminated Kite Shield",
        "Subsuming Spirit Shield",
        "Girded Tower Shield",
        "Thorium Spirit Shield",
        "Baroque Round Shield",
        "Sovereign Spiked Shield",
        "Golden Buckler",
        "Crested Tower Shield",
        "Angelic Kite Shield",
        "Lacewood Spirit Shield",
        "Ironwood Buckler",
        "Teak Round Shield",
        "Shagreen Tower Shield",
        "Alder Spiked Shield",
        "Branded Kite Shield",
        "Fossilised Spirit Shield",
        "Lacquered Buckler",
        "Ebony Tower Shield",
        "Champion Kite Shield",
        "Ezomyte Spiked Shield",
        "Spiny Round Shield",
        "Vaal Spirit Shield",
        "Vaal Buckler",
        "Ezomyte Tower Shield",
        "Mosaic Kite Shield",
        "Harmonic Spirit Shield",
        "Crusader Buckler",
        "Cardinal Round Shield",
        "Mirrored Spiked Shield",
        "Colossal Tower Shield",
        "Archon Kite Shield",
        "Titanium Spirit Shield",
        "Imperial Buckler",
        "Elegant Round Shield",
        "Cold-attuned Buckler",
        "Supreme Spiked Shield",
        "Transfer-attuned Spirit Shield",
        "Pinnacle Tower Shield",
        "Heat-attuned Tower Shield",
        "Deadhand Talisman",
        "Undying Flesh Talisman",
        "Rot Head Talisman",
        "Mandible Talisman",
        "Hexclaw Talisman",
        "Primal Skull Talisman",
        "Wereclaw Talisman",
        "Splitnewt Talisman",
        "Clutching Talisman",
        "Avian Twins Talisman",
        "Avian Twins Talisman",
        "Avian Twins Talisman",
        "Avian Twins Talisman",
        "Avian Twins Talisman",
        "Avian Twins Talisman",
        "Fangjaw Talisman",
        "Horned Talisman",
        "Spinefuse Talisman",
        "Three Rat Talisman",
        "Monkey Twins Talisman",
        "Longtooth Talisman",
        "Rotfeather Talisman",
        "Monkey Paw Talisman",
        "Monkey Paw Talisman",
        "Monkey Paw Talisman",
        "Three Hands Talisman",
        "Jet Amulet",
        "Black Maw Talisman",
        "Bonespire Talisman",
        "Ashscale Talisman",
        "Lone Antler Talisman",
        "Deep One Talisman",
        "Paua Amulet",
        "Coral Amulet",
        "Lapis Amulet",
        "Amber Amulet",
        "Jade Amulet",
        "Gold Amulet",
        "Citrine Amulet",
        "Turquoise Amulet",
        "Agate Amulet",
        "Simplex Amulet",
        "Onyx Amulet",
        "Writhing Talisman",
        "Chrysalis Talisman",
        "Ruby Amulet",
        "Marble Amulet",
        "Astrolabe Amulet",
        "Blue Pearl Amulet",
        "Full Leather",
        "Stygian Vise",
        "Chain Belt",
        "Rustic Sash",
        "Heavy Belt",
        "Leather Belt",
        "Golden Obi",
        "Cloth Belt",
        "Studded Belt",
        "Micro-Distillery Belt",
        "Mechalarm Belt",
        "Vanguard Belt",
        "Crystal Belt",
        "Arena Plate",
        "Breach Ring",
        "Iron Ring",
        "Coral Ring",
        "Paua Ring",
        "Sapphire Ring",
        "Topaz Ring",
        "Golden Hoop",
        "Jet Ring",
        "Ruby Ring",
        "Gold Ring",
        "Two-Stone Ring",
        "Two-Stone Ring",
        "Two-Stone Ring",
        "Geodesic Ring",
        "Cogwork Ring",
        "Diamond Ring",
        "Moonstone Ring",
        "Prismatic Ring",
        "Amethyst Ring",
        "Unset Ring",
        "Steel Ring",
        "Opal Ring",
        "Cerulean Ring",
        "Vermillion Ring",
        "Wyrmscale Doublet",
        "Latticed Ringmail",
        "Quilted Jacket",
        "Battle Plate",
        "Frontier Leather",
        "Silken Wrap",
        "Hussar Brigandine",
        "Crusader Chainmail",
        "Sleek Coat",
        "Glorious Leather",
        "Conjurer's Vestment",
        "Sun Plate",
        "Full Wyrmscale",
        "Ornate Ringmail",
        "Crimson Raiment",
        "Colosseum Plate",
        "Spidersilk Robe",
        "Coronal Leather",
        "Commander's Brigandine",
        "Chain Hauberk",
        "Lacquered Garb",
        "Cutthroat's Garb",
        "Destroyer Regalia",
        "Majestic Plate",
        "Battle Lamellar",
        "Devout Chainmail",
        "Savant's Robe",
        "Crypt Armour",
        "Sharkskin Tunic",
        "Golden Plate",
        "Dragonscale Doublet",
        "Loricated Ringmail",
        "Crusader Plate",
        "Sentinel Jacket",
        "Destiny Leather",
        "Necromancer Silks",
        "Desert Brigandine",
        "Conquest Chainmail",
        "Exquisite Leather",
        "Varnished Coat",
        "Astral Plate",
        "Occultist's Vestment",
        "Full Dragonscale",
        "Elegant Ringmail",
        "Widowsilk Robe",
        "Zodiac Leather",
        "Blood Raiment",
        "Gladiator Plate",
        "General's Brigandine",
        "Saint's Hauberk",
        "Glorious Plate",
        "Vaal Regalia",
        "Sadist Garb",
        "Assassin's Garb",
        "Triumphant Lamellar",
        "Saintly Chainmail",
        "Carnal Armour",
        "Sacrificial Garb",
        "Iron Greaves",
        "Rawhide Boots",
        "Wool Shoes",
        "Chain Boots",
        "Wrapped Boots",
        "Leatherscale Boots",
        "Steel Greaves",
        "Velvet Slippers",
        "Goathide Boots",
        "Ringmail Boots",
        "Strapped Boots",
        "Ironscale Boots",
        "Deerskin Boots",
        "Silk Slippers",
        "Plated Greaves",
        "Clasped Boots",
        "Mesh Boots",
        "Bronzescale Boots",
        "Scholar Boots",
        "Reinforced Greaves",
        "Nubuck Boots",
        "Shackled Boots",
        "Riveted Boots",
        "Steelscale Boots",
        "Antique Greaves",
        "Satin Slippers",
        "Eelskin Boots",
        "Zealot Boots",
        "Trapper Boots",
        "Serpentscale Boots",
        "Sharkskin Boots",
        "Samite Slippers",
        "Ancient Greaves",
        "Ambush Boots",
        "Soldier Boots",
        "Wyrmscale Boots",
        "Conjurer Boots",
        "Goliath Greaves",
        "Carnal Boots",
        "Shagreen Boots",
        "Legion Boots",
        "Hydrascale Boots",
        "Arcanist Slippers",
        "Vaal Greaves",
        "Stealth Boots",
        "Assassin's Boots",
        "Crusader Boots",
        "Dragonscale Boots",
        "Sorcerer Boots",
        "Titan Greaves",
        "Murder Boots",
        "Slink Boots",
        "Two-Toned Boots",
        "Iron Gauntlets",
        "Wool Gloves",
        "Rawhide Gloves",
        "Fishscale Gauntlets",
        "Wrapped Mitts",
        "Chain Gloves",
        "Goathide Gloves",
        "Plated Gauntlets",
        "Velvet Gloves",
        "Ironscale Gauntlets",
        "Strapped Mitts",
        "Ringmail Gloves",
        "Deerskin Gloves",
        "Bronze Gauntlets",
        "Silk Gloves",
        "Bronzescale Gauntlets",
        "Clasped Mitts",
        "Mesh Gloves",
        "Nubuck Gloves",
        "Steel Gauntlets",
        "Embroidered Gloves",
        "Steelscale Gauntlets",
        "Trapper Mitts",
        "Riveted Gloves",
        "Eelskin Gloves",
        "Antique Gauntlets",
        "Satin Gloves",
        "Zealot Gloves",
        "Serpentscale Gauntlets",
        "Sharkskin Gloves",
        "Ambush Mitts",
        "Samite Gloves",
        "Ancient Gauntlets",
        "Wyrmscale Gauntlets",
        "Carnal Mitts",
        "Soldier Gloves",
        "Goliath Gauntlets",
        "Shagreen Gloves",
        "Conjurer Gloves",
        "Legion Gloves",
        "Assassin's Mitts",
        "Hydrascale Gauntlets",
        "Arcanist Gloves",
        "Stealth Gloves",
        "Vaal Gauntlets",
        "Crusader Gloves",
        "Murder Mitts",
        "Dragonscale Gauntlets",
        "Sorcerer Gloves",
        "Titan Gauntlets",
        "Slink Gloves",
        "Spiked Gloves",
        "Fingerless Silk Gloves",
        "Gripped Gloves",
        "Iron Hat",
        "Vine Circlet",
        "Leather Cap",
        "Battered Helm",
        "Scare Mask",
        "Rusted Coif",
        "Cone Helmet",
        "Iron Circlet",
        "Plague Mask",
        "Tricorne",
        "Soldier Helmet",
        "Sallet",
        "Iron Mask",
        "Torture Cage",
        "Barbute Helmet",
        "Leather Hood",
        "Great Helmet",
        "Visored Sallet",
        "Tribal Circlet",
        "Close Helmet",
        "Festival Mask",
        "Wolf Pelt",
        "Crusader Helmet",
        "Gilded Sallet",
        "Bone Circlet",
        "Golden Mask",
        "Gladiator Helmet",
        "Secutor Helm",
        "Aventail Helmet",
        "Raven Mask",
        "Lunaris Circlet",
        "Reaver Helmet",
        "Hunter Hood",
        "Fencer Helm",
        "Zealot Helmet",
        "Callous Mask",
        "Noble Tricorne",
        "Siege Helmet",
        "Steel Circlet",
        "Lacquered Helmet",
        "Regicide Mask",
        "Great Crown",
        "Necromancer Circlet",
        "Ursine Pelt",
        "Samite Helmet",
        "Harlequin Mask",
        "Fluted Bascinet",
        "Magistrate Crown",
        "Solaris Circlet",
        "Ezomyte Burgonet",
        "Silken Hood",
        "Vaal Mask",
        "Pig-Faced Bascinet",
        "Prophet Crown",
        "Sinner Tricorne",
        "Royal Burgonet",
        "Mind Cage",
        "Deicide Mask",
        "Nightmare Bascinet",
        "Praetor Crown",
        "Eternal Burgonet",
        "Hubris Circlet",
        "Lion Pelt",
        "Bone Helmet",
        "Splintered Tower Shield",
        "Goathide Buckler",
        "Twig Spirit Shield",
        "Corroded Tower Shield",
        "Spiked Bundle",
        "Rotted Round Shield",
        "Plank Kite Shield",
        "Pine Buckler",
        "Yew Spirit Shield",
        "Rawhide Tower Shield",
        "Driftwood Spiked Shield",
        "Fir Round Shield",
        "Linden Kite Shield",
        "Bone Spirit Shield",
        "Painted Buckler",
        "Cedar Tower Shield",
        "Studded Round Shield",
        "Reinforced Kite Shield",
        "Alloyed Spiked Shield",
        "Tarnished Spirit Shield",
        "Hammered Buckler",
        "Copper Tower Shield",
        "Burnished Spiked Shield",
        "Layered Kite Shield",
        "Scarlet Round Shield",
        "Jingling Spirit Shield",
        "War Buckler",
        "Exothermic Tower Shield",
        "Endothermic Buckler",
        "Reinforced Tower Shield",
        "Exhausting Spirit Shield",
        "Splendid Round Shield",
        "Ornate Spiked Shield",
        "Brass Spirit Shield",
        "Ceremonial Kite Shield",
        "Gilded Buckler",
        "Painted Tower Shield",
        "Walnut Spirit Shield",
        "Oak Buckler",
        "Redwood Spiked Shield",
        "Buckskin Tower Shield",
        "Maple Round Shield",
        "Etched Kite Shield",
        "Ivory Spirit Shield",
        "Eled Buckler",
        "Mahogany Tower Shield",
        "Spiked Round Shield",
        "Ancient Spirit Shield",
        "Compound Spiked Shield",
        "Corrugated Buckler",
        "Steel Kite Shield",
        "Bronze Tower Shield",
        "Chiming Spirit Shield",
        "Polished Spiked Shield",
        "Crimson Round Shield",
        "Polar Buckler",
        "Magmatic Tower Shield",
        "Battle Buckler",
        "Laminated Kite Shield",
        "Subsuming Spirit Shield",
        "Girded Tower Shield",
        "Thorium Spirit Shield",
        "Baroque Round Shield",
        "Sovereign Spiked Shield",
        "Golden Buckler",
        "Crested Tower Shield",
        "Angelic Kite Shield",
        "Lacewood Spirit Shield",
        "Ironwood Buckler",
        "Teak Round Shield",
        "Shagreen Tower Shield",
        "Alder Spiked Shield",
        "Branded Kite Shield",
        "Fossilised Spirit Shield",
        "Lacquered Buckler",
        "Ebony Tower Shield",
        "Champion Kite Shield",
        "Ezomyte Spiked Shield",
        "Spiny Round Shield",
        "Vaal Spirit Shield",
        "Vaal Buckler",
        "Ezomyte Tower Shield",
        "Mosaic Kite Shield",
        "Harmonic Spirit Shield",
        "Crusader Buckler",
        "Cardinal Round Shield",
        "Mirrored Spiked Shield",
        "Colossal Tower Shield",
        "Archon Kite Shield",
        "Titanium Spirit Shield",
        "Imperial Buckler",
        "Elegant Round Shield",
        "Cold-attuned Buckler",
        "Supreme Spiked Shield",
        "Transfer-attuned Spirit Shield",
        "Pinnacle Tower Shield",
        "Heat-attuned Tower Shield",
        "Aberrant Fossil",
        "Aetheric Fossil",
        "Bloodstained Fossil",
        "Bound Fossil",
        "Corroded Fossil",
        "Dense Fossil",
        "Enchanted Fossil",
        "Encrusted Fossil",
        "Faceted Fossil",
        "Fractured Fossil",
        "Frigid Fossil",
        "Gilded Fossil",
        "Glyphic Fossil",
        "Hollow Fossil",
        "Jagged Fossil",
        "Lucent Fossil",
        "Metallic Fossil",
        "Perfect Fossil",
        "Prismatic Fossil",
        "Pristine Fossil",
        "Sanctified Fossil",
        "Scorched Fossil",
        "Serrated Fossil",
        "Shuddering Fossil",
        "Tangled Fossil",
        "Prime Chaotic Resonator",
        "Prime Alchemical Resonator",
        "Powerful Chaotic Resonator",
        "Powerful Alchemical Resonator",
        "Potent Chaotic Resonator",
        "Potent Alchemical Resonator",
        "Primative Chaotic Resonator",
        "Primative Alchemical Resonator",
        "Simulacrum",
        "Simulacrum Splinter",
        "Intrinsic Catalyst",
        "Prismatic Catalyst",
        "Fertile Catalyst",
        "Tempering Catalyst",
        "Abrasive Catalyst",
        "Imbued Catalyst",
        "Turbulent Catalyst",
        "Fragment of Emptiness",
        "Fragment of Terror",
        "Fragment of Knowledge",
        "Fragment of Shape",
        "Fragment of Purification",
        "Fragment of Constriction",
        "Fragment of Eradication",
        "Fragment of Enslavement",
        "Timeless Vaal Emblem",
        "Timeless Templar Emblem",
        "Timeless Eternal Emblem",
        "Timeless Maraketh Emblem",
        "Timeless Karui Emblem",
        "Chayula's Pure Breachstone",
        "Uul-Netol's Pure Breachstone",
        "Esh's Pure Breachstone",
        "Tul's Pure Breachstone",
        "Xoph's Pure Breachstone",
        "Chayula's Enriched Breachstone",
        "Uul-Netol's Enriched Breachstone",
        "Esh's Enriched Breachstone",
        "Tul's Enriched Breachstone",
        "Xoph's Enriched Breachstone",
        "Chayula's Charged Breachstone",
        "Uul-Netol's Charged Breachstone",
        "Esh's Charged Breachstone",
        "Tul's Charged Breachstone",
        "Xoph's Charged Breachstone",
        "Chayula's Breachstone",
        "Esh's Breachstone",
        "Tul's Breachstone",
        "Xoph's Breachstone",
        "Uul-Netol's Breachstone",
        "Offering to the Goddess",
        "Fragment of the Chimera",
        "Fragment of the Minotaur",
        "Fragment of the Phoenix",
        "Fragment of the Hydra",
        "Volkuur's Key",
        "Inya's Key",
        "Yriel's Key",
        "Eber's Key",
        "Mortal Hope",
        "Mortal Ignorance",
        "Mortal Rage",
        "Mortal Grief",
        "Sacrifice at Noon",
        "Sacrifice at Dawn",
        "Sacrifice at Midnight",
        "Sacrifice at Dusk",
        "Cobalt Jewel",
        "Crimson Jewel",
        "Viridian Jewel",
        "Small Cluster Jewel",
        "Medium Cluster Jewel",
        "Large Cluster Jewel",
        "Ghastly Eye Jewel",
        "Hypnotic Eye Jewel",
        "Murderous Eye Jewel",
        "Searching Eye Jewel",
        "Siege Map",
        "Courthouse Map",
        "Underground River Map",
        "Relic Chambers Map",
        "Necropolis Map",
        "Maze Map",
        "Promenade Map",
        "Cemetery Map",
        "Harbinger Map",
        "Atoll Map",
        "Shore Map",
        "Underground Sea Map",
        "Bone Crypt Map",
        "Dunes Map",
        "Temple Map",
        "Basilica Map",
        "Harbinger Map",
        "Harbinger Map",
        "Harbinger Map",
        "Cursed Crypt Map",
        "Chateau Map",
        "Museum Map",
        "Moon Temple Map",
        "Courtyard Map",
        "Park Map",
        "Tropical Island Map",
        "Vaal Pyramid Map",
        "Strand Map",
        "Two-Point Arrow Quiver",
        "Serrated Arrow Quiver",
        "Sharktooth Arrow Quiver",
        "Blunt Arrow Quiver",
        "Fire Arrow Quiver",
        "Broadhead Arrow Quiver",
        "Penetrating Arrow Quiver",
        "Ornate Quiver",
        "Spike-Point Arrow",
        "Small Life Flask",
        "Medium Life Flask",
        "Large Life Flask",
        "Greater Life Flask",
        "Grand Life Flask",
        "Giant Life Flask",
        "Colossal Life Flask",
        "Sacred Life Flask",
        "Hallowed Life Flask",
        "Sanctified Life Flask",
        "Divine Life Flask",
        "Eternal Life Flask",
        "Small Mana Flask",
        "Medium Mana Flask",
        "Large Mana Flask",
        "Greater Mana Flask",
        "Grand Mana Flask",
        "Giant Mana Flask",
        "Colossal Mana Flask",
        "Sacred Mana Flask",
        "Hallowed Mana Flask",
        "Sanctified Mana Flask",
        "Divine Mana Flask",
        "Eternal Mana Flask",
        "Small Hybrid Flask",
        "Medium Hybrid Flask",
        "Large Hybrid Flask",
        "Colossal Hybrid Flask",
        "Sacred Hybrid Flask",
        "Hallowed Hybrid Flask",
        "Quicksilver Flask",
        "Bismuth Flask",
        "Stibnite Flask",
        "Amethyst Flask",
        "Ruby Flask",
        "Sapphire Flask",
        "Topaz Flask",
        "Silver Flask",
        "Aquamarine Flask",
        "Granite Flask",
        "Jade Flask",
        "Quartz Flask",
        "Sulphur Flask",
        "Basalt Flask",
        "Diamond Flask"
    };
}
