<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net9.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<TreatWarningsAsErrors>true</TreatWarningsAsErrors>
	</PropertyGroup>

	<ItemGroup>
	  <None Remove="ChromeCookiesView.cfg" />
	  <None Remove="ChromeCookiesView.exe" />
	</ItemGroup>

	<ItemGroup>
	  <Content Include="ChromeCookiesView.exe">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </Content>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="AlphaFS.New" />
		<PackageReference Include="AlphaVSS" />
		<PackageReference Include="CliWrap" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
		<PackageReference Include="Microsoft.Extensions.Http" />
		<PackageReference Include="Microsoft.Extensions.Logging.Console" />
		<PackageReference Include="RateLimiter" />
		<PackageReference Include="Nito.AsyncEx" />
	</ItemGroup>

</Project>
